<?php

namespace IMG\ShopBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchCategories($showEmpty = false){
        $qb = $this->createQueryBuilder('c');
        if (!$showEmpty) {
            $qb->join('c.items', 'i');
        }
        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
