<?php

namespace IMG\ShopBundle\Repository;

/**
 * finalizedOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class finalizedOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
