<?php

namespace UserBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found.
     *
     * @param string $username The username
     *
     * @return object
     */
    public function loadUserByUsername($username)
    {
        $user = $this->findOneBy([
           'username' => $username
        ]);

        if (!$user) {
            $user = $this->findOneBy([
                'email' => $username
            ]);
        }

        return $user;

    }
}
